[package]
name = "pong"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = { version = "0.12.0", features = ["nightly"] }

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
